### ISSUE TITLE
update docs main page

### ISSUE THREAD

**Issue by miquelvir** [miquelvir/xals#1]
**current**
the docs show the items "pre-enrolment", "payments" and "attendance", and their descriptions.

**desired**
the docs show updated titles and descriptions for Xals

**useful code**
this lives here: `docs/src/components/HomepageFeatures.js`

**acceptance criteria**
- [ ] the docs have updated feature titles (relevant to Xals)
- [ ] the docs have updated feature descriptions (relevant to Xals)

**Comment by carlota10** [comment]
i take this
