### ISSUE TITLE
table cards UI is improved

### ISSUE THREAD

**Issue by miquelvir** [miquelvir/xals#15]
**current**
the UI is just the barebones component

**desired**
the UI looks nice and modern

**useful**
go to `/app/restaurant` in the browser to see a sample use of the tiles
this code lives in `web_app/src/pages/restaurantDashboardPage/restaurantDashboardPage.js`

- [x] the card takes different colors (green, yellow/orange, red) according to the `table.status` (`['ok', 'warning', 'late']`)
- [x] the card displays the time from the last served course
- [x] the card displays the table number

**Comment by nereasastre** [comment]
i (try to) do this

**Comment by miquelvir** [comment]
![image](https://user-images.githubusercontent.com/41950283/136599450-999185de-cd06-4106-9789-1675fc6280c6.png)
